
<div class="content-proximamente">
    <div class="banner-1">
    	<img src="{{ asset('clientlibs/img/ganadores.png') }}" alt="Engie"></div>
    <div class="banner-2">
    	<img src="{{ asset('clientlibs/img/ganadores_mob.png') }}" alt="Engie"></div>
    <div class="clearfix"></div>
</div>



<div class="container">


	<div class="row">
		<div class="col-md-4">
			<div class="titulo">Estado de México</div>
			<ul class="lista">
<li>MARIO HERNÁNDEZ VARGAS</li>
<li>ANA SERRANO</li>
<li>JUANARTURO ALVAREZPEREZ</li>
<li>ROSA CERVANTES</li>
<li>PATRICIA GODINEZ</li>
<li>RAUL DELGADO</li>
<li>FRANCISCO HERNÁNDEZ</li>
<li>HECTOR MENDEZ</li>
<li>ELIZABETH FLORES MONDRAGON</li>
<li>MARTHA ELVIRA CUEVAS JACINTO</li>
<li>CUAUHTEMOC RODRIGUEZ</li>
<li>JESUS BRAVO</li>
<li>ROCIO CATALINA NAVA</li>
<li>RAFAEL LEON</li>
<li>JOSÉ GABRIEL CRUZ BECERRA</li>
<li>EPIFANIA GONZALEZ</li>
<li>JAVIER MACIEL400</li>
<li>MARIOALBERTO AYALARAMOS</li>
<li>ALFONSO PEÑA</li>
<li>JESUS ARIAS</li>
<li>JOSELUIS GUADARRAMAMENDEZ</li>
<li>RODRIGO ROSAS</li>
<li>JUAN DANIEL MARTINEZ</li>
<li>RAMON DIAZ</li>
<li>RICARDO CHAZARO</li>
<li>MARCELA ORDOÑEZ BELMAN</li>
<li>DAVID ALEJANDRO LÓPEZ ZAPATA</li>
<li>MARCIANO CONDE</li>
<li>DOLORES HERNANDEZ</li>
<li>CLAUDIA GARCÍA</li>
<li>HUGO ALBERTO CHAVERO SANTANA</li>
<li>JES√∫S TOVAR</li>
<li>JOSÉ LUIS CHÁVEZ</li>
<li>FRANCO PEREZ</li>
<li>EUNICE HERNANDEZ</li>
<li>JORGE SANTOS</li>
<li>DAVIDALEXIS SÁNCHEZMEDINA</li>
<li>FEDERICO CONTRERAS</li>
<li>MARCO VARGAS</li>
<li>ANA GUERRA</li>
<li>ARMANDO GOMEZ</li>
<li>IVONNEKARINA LESSER</li>
<li>RUBEN BARBA</li>
<li>EDUARDO ESTRADA</li>
<li>ELISA PETRICIOLI</li>
<li>MIGUEL AVILA</li>
<li>LUIS SANTOS</li>
<li>ZEFERINO GARCÍA</li>
<li>AMALIA VÁZQUEZ</li>
<li>EDUARDO ORTEGA ARELLANO</li>
<li>JOCELYN RAMÍREZ</li>
<li>MARCO ANTONIO GONZALEZ BRAVO</li>
<li>ERIK ALCARAZ</li>
<li>MARIA DE JESUS CRUZ CORPUS</li>
<li>ARTURO SANCHEZ SALINAS</li>
<li>SERGIO ISRAEL CARCAMO</li>
<li>MANUEL MUÑOZ JIMENEZ</li>
<li>RUBEN ALFONSO MEZA MARTINEZ</li>
<li>IVONNE BRAVO</li>
<li>ROSALBA MURILLO MERINO</li>
<li>LUISA BEATRIZ VILLALOBOS LOPEZ</li>
<li>RICARDO OLIVERIO RODRÍGUEZ TÉLLEZ</li>
<li>OLGA MORALES</li>
<li>EDMUNDO HITA</li>
<li>CARMEN LUCÍA BAUTISTA</li>
<li>JOSE LUIS RODRIGUEZ PEREZ</li>
<li>EUGENIO GONZALEZBARRAGAN</li>
<li>JESSICA FUENTES</li>
<li>JUAN OSCAR GUTIERREZ ESPINO</li>
<li>MARIAAZUCENA SANCHEZ</li>
<li>SALVADOR ROMERO</li>
<li>ENGRACIA CRUZ</li>
<li>FRANCISCO VELASCO</li>
<li>JOSÉ RODOLFO SANCHEZ</li>
<li>BEATRIZ MOLINA</li>
<li>EVELYN RODRIGUEZ</li>
<li>EDUARDO JIMENEZ</li>
<li>DAVID LEDEZMA</li>
<li>PILAR TREJO</li>
<li>GUILLERMINA PEÑA</li>
<li>VICTOR RAFAEL GARCÍA GARCÉS</li>
<li>GRACIELA CARO LOPEZ</li>
<li>AURELIO ESCANDON</li>
<li>VICTOR MANUEL RAMIREZ ESTRADA</li>
<li>JUAN CARLOS LEMUS</li>
<li>SOSIMA MUNOZ</li>
<li>JUSTO DAMIAN</li>
<li>TRINIDAD LOPEZ GUTIERREZ</li>
<li>EFRAIN MORA</li>
<li>MARIA DE LOS DOLORES MONTOYA RUIZ</li>
<li>MARÍA GUADALUPE OCAMPO ARANGO</li>
<li>JUAN GONZALEZ</li>
<li>JORGE PORTILLA</li>
<li>JORGE ALCAZAR GARGALLO</li>
<li>RAUL ERICK GARCIA MONTANTES</li>
<li>PATRICIA GARCÍA</li>
<li>ELIZABETH CHAVEZ</li>
<li>GUILLERMO HERNANDEZ</li>
<li>CARLOS CARRILLO</li>
<li>LUIS GUTIERREZ</li>
<li>VICENTE TERRAZAS</li>
<li>ANGÉLICA RODRÍGUEZ</li>
<li>BALVINA ARREOLA</li>
<li>EMMA RODRIGUEZ</li>
<li>MARÌA GUADALUPE MAR ARÈVALO</li>
<li>JOSÉ EDUARDO BETANCOURT</li>
<li>GENOVEVA DE LA TORRE NAVARRO</li>
<li>GUADALUPE CRUZ</li>
<li>ESTHER URQUIETA</li>
<li>HECTOR MENDIETA</li>
<li>EDITH PAREDES</li>
<li>JOSE GONZALEZ</li>
<li>DAVID BENITEZ</li>
<li>FILIBERTO VILLAGOMEZ</li>
<li>IRAIS MORALES</li>
<li>RODRIGO FLORES</li>
<li>BENJAMÍN RODRÍGUEZ</li>
<li>FERNANDO MARTINEZ</li>
<li>GUADALUPE GUTIERREZ</li>
<li>SUSANA YAÑEZ</li>
<li>PATRICIA CARMONA</li>
<li>LINDA JENNYFER GOMEZ MENDEZ</li>
<li>JAIME MARTINEZ</li>
<li>JOSE SANTOS GABRIEL QUINTANA AVILA</li>
<li>ENRIQUE SÁNCHEZ</li>
<li>MARTIN ZAMUDIO</li>
<li>PATRICIA RIVERA</li>
<li>RICARDO OCAMPO</li>
<li>LETICIA RÍOS</li>
<li>FRANCISCO REBOLLO</li>
<li>OSCAR ORTIZ</li>
<li>EMMA FERNANDEZ MIRANDA</li>
<li>ANTONIO TORRES DOMINGUEZ</li>
<li>MERCEDES MARTINEZ</li>
<li>RUTH NOEMI VÁZQUEZ CERÓN</li>
<li>BERTHA ROMERO</li>
<li>ESTEBAN CANSECO ARAGON</li>
<li>FEDERICO DE LA ROSA MENDOZA</li>
<li>ANTONIO CORREA</li>
<li>GERARDO PEREZ</li>
<li>LAURA LUJA</li>
<li>PEDRO CHILPA</li>
<li>LETICIA MORONES</li>
<li>DANIEL GARCIA</li>
<li>BLANCA MENESES</li>
<li>ABRAHAM SORKIN</li>
<li>JULIÁN RAZO</li>
<li>RAMON DANIEL HORTA</li>
<li>ANAMARIA OLIVO</li>
<li>LUZ BAHENA</li>
<li>ALEJANDRO CARBAJAL</li>
<li>SANDRA MORENO</li>
<li>AURORA ACOSTA</li>
<li>ELOISA OSORIO</li>
<li>ANDREA GARCÍA</li>
<li>JORGE MEDINA</li>
<li>MANUEL SANTIAGO</li>
<li>GERARDO ALCANTARA</li>
<li>ALICIA CHIQUINI</li>
<li>EVA ALMAZAN</li>
<li>VICTOR RAFAEL RICO</li>
<li>ALEJANDRO DE LA TORRE PUNZO</li>
<li>MARIA GUADALUPE HERNANDEZ CARREON</li>
<li>ERNESTO ARANDA</li>
<li>FRUCTOSO GERARDO ARONTES GARCIA</li>
<li>VIANEY BARRAGAN</li>
<li>MARCELA PEREZMONDRAGON</li>
<li>ESTHER QUIROZ</li>
<li>OLIVIA ZUNIGASEGOVIA</li>
<li>JESUS LOPEZ</li>
<li>JULIO CESAR CUELLAR BAUTISTA</li>
<li>ALEJANDRO ALDANA</li>
<li>CARLOS GUTIERREZ</li>
<li>ASCENCION JACOBOCARRILLO</li>
<li>CYNTHIA MENENDEZ</li>
<li>GRACIELA RAMIREZ MALDONADO</li>
<li>ANTONIO CARBAJAL</li>
<li>SERGIO DAVILA ORTIZ</li>
<li>MARIBEL GARCÍA</li>
<li>YOLANDA MONARREZ</li>
<li>JOSE ALFREDO JIMENEZ BACA</li>
<li>LEONARDO CONTRERAS</li>
<li>LUIS ZARCO</li>
<li>SARA SANCHEZ</li>
<li>SERGIO AONSO</li>
<li>JUAN FLORES</li>
<li>CRISTINA MIRANDA RODRÍGUEZ</li>
<li>MARIA TAURINA ROCHA ZAMARRON</li>
<li>GUSTAVO BLANCAS</li>
<li>LUCIA SILVA</li>
<li>GUSTAVO QUIJANO</li>
<li>ROBERTO JUAREZ</li>
<li>ALBERTO CRUZ</li>
<li>YOLANDA CORTES</li>
<li>VICTORHUGO RIVERACHACON</li>
<li>SANDRA BARRERA</li>
<li>GUSTAVO VALENCIA TOPETE</li>
<li>VICTOR HUGO DAMIAN ORTA VILLEGAS</li>
<li>MARÍA  VICENTA AREVALO CAZARES</li>
<li>JOSÉ CRUZ</li>
<li>ALEJANDRO BONILLA</li>
<li>GUADALUPE VILLEGAS</li>
<li>VERENICE HUCHIN</li>
<li>KATHERINE RAFAEL</li>
<li>HUGO ALMAZAN</li>
<li>SALVADOR MACARIO HERNANDEZ CORONA</li>
<li>JOSE GERARDO MARTINEZ VAZQUEZ</li>
<li>ULISES HERNANDEZ</li>
<li>MARIAALICIA DOMINGUEZBRAVO</li>
<li>RICARDO BENÍTEZ</li>
<li>JOSELUIS ABOITES</li>
<li>VICENTE ABURTO</li>
<li>MONICA CARBAJAL</li>
<li>MAURICIO CORTES</li>
<li>MARIA GUADALUPE CASTRO GONZALEZ</li>
<li>MARCO SIERRA</li>
<li>JOSÉ ANTONIO IBARRA</li>
<li>JOSE LUIS GRAJALES GONZALEZ</li>
<li>RICRDO ALARCON</li>
<li>JESUS SANCHEZ</li>
<li>GUILLERMO GUERRERO</li>
<li>ARSENIA MARTÍNEZ CRUZ</li>
<li>CRISTIAN GUILLERMO TELLEZ JIMENEZ</li>
<li>SEBASTIANA ORDOÑEZ</li>
<li>IGNACIO BUSTOS</li>
<li>RANFERI GOMEZ DUARTE</li>
<li>LILIANA RODRIGUEZ</li>
<li>ELBA BUSTAMANTE</li>
<li>CARLOS QUINTANA</li>
<li>FRANCISCO DONIS</li>
<li>HIPOLITA PATRICIA SALAZAR FUENTES</li>
<li>ANTONIO GONZALEZ</li>
<li>OLIVIA CHAVEZ</li>
<li>EUTIMIO NAVARRETE</li>
<li>LUIS PALACIOS</li>
<li>UBALDO CENTENO</li>
<li>ROGELIO ALVAREZ</li>
<li>ZULEMA PRADO</li>
<li>ROBERTO MORALES</li>
<li>SALOME GARCIA ARRIAGA</li>
<li>OLIVERFARITH SANCHEZRAMIREZ</li>
<li>ANGELICA NÚÑEZ</li>
<li>MARIADEJESUS SANCHEZ</li>
<li>MARÍA DE LA LUZ GUADARRAMA CRUZ</li>
<li>SERGIO CASTRO</li>
<li>LEOPOLDO TENA</li>
<li>ALFONSO SOSA</li>
<li>MA SANTA DIAZ GARCIA</li>
<li>GERARDO JACOME</li>
<li>GUADALUPE GONZALEZ</li>
<li>CATALINA MARIOTT </li>
</ul>

		</div>
		<div class="col-md-4" style="background: rgba(0,173,239,.05)">
			<div class="titulo">Puebla</div>

<ul class="lista">
<li>MARIA DEL SOCORRO FONSECA GONZALEZ</li>
<li>MARTÍN VAZQUEZ</li>
<li>ELIA ISALIA VELAZQUEZ ANTONIO</li>
<li>MARYCRUZ GOMEZLINARES</li>
<li>MIGUELANGELR FERNÁNDEZDELARAA</li>
<li>ALBINO ARRAMBIDE</li>
<li>ALFREDO ALATORRE</li>
<li>OSVALDO TLAHUIS PORTILLO</li>
<li>SIMON GRANADOS</li>
<li>ANGÉLICA SALINAS ESCALERA</li>
<li>ENRIQUE SANCHEZ</li>
<li>AARON DIAZ</li>
<li>SOLEDAD GARCIA</li>
<li>RAFAEL BONILLA</li>
<li>SALVIRRUBI MAGAÑA</li>
<li>FELIPE ISIDRO SANCHEZ ALDUCIN</li>
<li>JULIETA RIVERA</li>
<li>CAYETANO SANCHEZ</li>
<li>ARMINDA JUDITH CRESPO CHAVEZ</li>
<li>MARIA SALOME CAMPANARIO</li>
<li>FRANCISCO PEREZ</li>
<li>FRANCISCO MUNIVE</li>
<li>MARIA GONZALEZ</li>
<li>MARCOS RAMOS</li>
<li>MARCOS SALDANA</li>
<li>CHRISTIAN MESTERN WITTERN</li>
<li>JUAN RIVAS FIGUEROA</li>
<li>LETICIA CAZARES</li>
<li>TERESA ORTEGA ROCHA</li>
<li>REBECA SANCHEZ</li>
<li>MARÍA ANGELINA AMÉZQUITA LIMA</li>
<li>ARMANDO SOTO</li>
<li>VICTOR ORTEGA</li>
<li>ALBERTO CUETO PEREZ</li>
<li>ROSA GONZALEZ</li>
<li>ENRIQUE HEREDIA</li>
<li>SOCORRO RIOS</li>
<li>TERESA CATZALCO</li>
<li>SANDRA SANCHEZ</li>
<li>ALEJANDRO SANCHEZ</li>
<li>JOSEROBERTO ROJASMARTINEZ</li>
<li>FRANCISCO DE ZATARAIN RIVERO</li>
<li>ALEJANDRO FRAGA</li>
<li>ALEJANDRO HATUNI NEKUZI</li>
<li>RAMÓN GONZÁLEZ</li>
<li>GILBERTO BRIBIESCA AGUILAR</li>
<li>EMILIO PALACIOS MENESES</li>
<li>MIGUEL ANGEL TOBON</li>
<li>CINTHYA MONTSERRAT TOVAR LÓPEZ</li>
<li>HUMBERTO HERNÁNDEZ</li>
<li>LUZ MARIA GONZALEZ</li>
<li>VERONICA RIVERA ORTIZ</li>
<li>GLORIA GUEVARA</li>
<li>MANUEL TORRES</li>
<li>MERCEDES GAMBOA</li>
<li>BLANCA LILIA BAGATELLA</li>
<li>LETICIA CAMARILLO</li>
<li>OLIMPIA JARAMILLO</li>
<li>GUSTAVO ESPINOSA DELGADO</li>
<li>MARICRUZ GONZÁLEZ</li>
<li>JACOBO MOTA</li>
<li>ANTONIO SANCHEZ</li>
<li>ARMANDO ROMERO</li>
<li>ISMAEL DE JESUS SANCHEZ</li>
<li>LEOBARDO HERRERA</li>
<li>ADRIAN CAMPOS</li>
<li>ÁNGELES DEL CARNEN LOBATO CONTRERAS</li>
<li>EMILIO OROZCO GARCÍA</li>
<li>JESSICA CARRERA</li>
<li>IRENE ROMERO</li>
<li>DANIEL SANLUIS</li>
<li>YOLIVETH BERMUDEZ</li>
<li>CARLOS CHAIREZ</li>
<li>FRANCISO NOGUEZ</li>
<li>JORGE FIERRO</li>
<li>GLADYS MENDOZA TORRES</li>
<li>OLGA FRANCO CRUZ</li>
<li>SAMANTA FAJARDO</li>
<li>IGNACIO LOPEZ TELLEZ</li>
<li>GUILLERMO NUÑEZ</li>
<li>GABRIEL BUSTILLOS</li>
<li>MARIA ELEUTERIA LEAL AGUILAR</li>
<li>JEANETTE DOMINGUEZ</li>
<li>EDUARDO JOSÉ LÓPEZ GARCÍA</li>
<li>ROSA JOSEFINA AGUILA REYES</li>
<li>GUISELA GALARZA GOMEZ</li>
<li>MARTHA SAN MARTÍN GARCÍA</li>
<li>ESTELA MARTINEZ</li>
<li>CARLOS ROLANDO ORTÍZ CARRANCO</li>
<li>RAFAEL LIMON</li>
<li>RODRIGO IVÁN CONDE CRUZ</li>
<li>ALEJANDRA ARANGO</li>
<li>VICTOR MANUEL DEL POZO GONZÁLEZ</li>
<li>KARINA MESTERN</li>
<li>ALICIA MUGARTEGUI</li>
<li>MARÍA EUGENIA MÉNDEZ</li>
<li>JOSE RAMIREZ</li>
<li>DANIEL BOY PAGAZA</li>
<li>GILBERTO FLORES</li>
<li>ELIA HERRERA</li>
<li>TANIA GUADALUPE ESCALANTR GAXIOLA</li>
<li>MARCELINA CASTAÑEDA</li>
<li>CAROLINA GUTIERREZ</li>
<li>PABLO HUETLE</li>
<li>DELIA SOLANO</li>
<li>SANDY CECILIA OROZCO VELÁZQUEZ</li>
<li>VIVIANA RIVERA</li>
<li>FRANCISCO JAVIER CORONA AGUIRRE</li>
<li>FRANCISCO DE JESÚS LARA HERNÁNDEZ</li>
<li>ROCIO CADENA</li>
<li>JOSE JUAN VILLARRUEL PRECIADO</li>
<li>FLORENCIA HERNANDEZ AGUILAR</li>
<li>MARCOS CASTELLANOS</li>
<li>RAUL ESPINOSA</li>
<li>DAVID ABEL CATALAN REYES</li>
<li>GUILLERMO SANCHEZ CARREON</li>
<li>JOSE ANTONIO CARDOSO MARIN</li>
<li>CATALINA CRUZ PALAFOX</li>
<li>ABRAHAM HERNÁNDEZ</li>
<li>JOEL ESPINOZA MONTES</li>
<li>RAMON VILLEGAS</li>
<li>PATRICIA GARCIA</li>
<li>MARÍA JUANA JOSEFINA RAMÍREZ MARTÍNEZ</li>
<li>LOURDES AGUAYO</li>
<li>MAX TECUANHUEHUE</li>
<li>ADRIANA ROSALES</li>
<li>MARIA RODRIGUEZ</li>
<li>ELIZABETH OROPEZA</li>
<li>MARIA GUADALUPE LOPEZ GARGALLO</li>
<li>SEBERIANO PEREZ</li>
<li>RAUL VERGARA RAMIREZ</li>
<li>YOLANDA MARQUEZ</li>
<li>RAQUEL LÓPEZ</li>
<li>GUADALUPE ARMENTA</li>
<li>LUZ MARIA VARGAS ABREGO</li>
<li>IVAN MANZANO</li>
<li>GUMARO CHAVEZ</li>
<li>EVERARDO PUGA</li>
<li>VIANNEY SEDAS</li>
<li>YOLANDA CASTILLO MONDRAGON</li>
<li>MARINA RUIZ</li>
<li>MARIASOLEDAD HURTADO</li>
<li>LUCIA ARCE GAMONEDA</li>
<li>YOLANDA JUAREZ</li>
<li>ERENDIRA CASTILLO</li>
<li>CARLOS HERNÁNDEZ PÉREZ</li>
<li>JORGE HUMBERTO HERNANDEZ ROLDAN</li>
<li>LUIS ENRIQUE RUIZ</li>
<li>ALMA IVONNE ELVIRA</li>
<li>LETICIA LOPEZ</li>
<li>ANA LUCILA AMBROSIO GONZALEZ</li>
<li>DAVID SERRATO URRUCHÚA</li>
<li>RUBEN ALVAREZ</li>
<li>VICTOR HUGO MARTINEZ JUAREZ</li>
<li>ALEJANDRA BARRANCO</li>
<li>ADRIANA TREVIÑO</li>
<li>RODOLFO RICARDO SANDOVAL RODRÍGUEZ</li>
<li>GERARDO MENDEZ</li>
<li>BLAS MEDINA LOPEZ</li>
<li>LIDIA LÓPEZ DÍAZ</li>
<li>JUANCARLOS NAVATORNEL</li>
<li>REBECA SILVA</li>
<li>BLANCA BRIONES</li>
<li>ROBERTO GONZALEZ</li>
<li>JUAN ALEJANDRO FERNANDEZ</li>
<li>JUANPABLO HERNANDEZ</li>
<li>ROSA GOMEZ</li>
<li>ROBERTO FEDERICO GARCÍA GARCÍA</li>
<li>EDUARDO AVALOS</li>
<li>ROMAN JIMÉNEZ</li>
<li>ISABEL ROJAS</li>
<li>JELLEL RAMIREZVILLEGAS</li>
<li>JORGE MENDOZA</li>
<li>ANTONIO MUNOZ</li>
<li>MARIA FCA CRISTINA PARRA OREA</li>
<li>JOSÉ FRANCISCO ESPINOZA  LEZAMA</li>
<li>CECILIA ROMERO VILLA</li>
<li>ISMAEL GARRIDO</li>
<li>CONCEPCIÓN MORENO PÉREZ</li>
<li>REGINO LICONA</li>
<li>JUAN MANUEL CARRETO CALVARIN</li>
<ul>
			


		</div>
		<div class="col-md-4">
			<div class="titulo">Querétaro</div>
<ul class="lista">
<li>SERGIO MONTERO</li>
<li>JOSE VELAZQUEZ NARANJO</li>
<li>FRANCISCO DELGADO</li>
<li>MARICELA HERNANDEZ</li>
<li>RAUL BADILLO</li>
<li>MARGARITA MENDOZA</li>
<li>CRISTINA AVILA</li>
<li>GUILLERMINA JUAREZ</li>
<li>NORMA CURIEL</li>
<li>ARTURO VERA</li>
<li>HÉCTOR MORALES SÁNCHEZ</li>
<li>JUAN JOSE HERNANDEZ LUIS</li>
<li>ADAN SORIANO</li>
<li>RAFAEL SOTO</li>
<li>MA. DE LOURDES GARCIA CENTENO</li>
<li>MARTINA TORRES</li>
<li>MARIA PERALES</li>
<li>ANGELINA GONZALEZ</li>
<li>VÍCTOR GARCÍA</li>
<li>ALAN BARRON CORONEL</li>
<li>ANTONIO VARGAS</li>
<li>ESTHER LOPEZ</li>
<li>ARMANDO GUTIERREZ</li>
<li>JOEL ENCISO</li>
<li>SERGIO SALAZAR</li>
<li>LUZ MARTINEZ</li>
<li>MARIANNE GONZÁLEZ</li>
<li>MACONSUELO BAEZABAEZA</li>
<li>MAYRA MENDOZA RICO</li>
<li>JUAN ANTONIO COELLO</li>
<li>MARIA DEL CARMEN GONZALEZ HERNANDEZ</li>
<li>MARÍA EUGENIA MARTÍNEZ HERNÁNDEZ</li>
<li>ALEJANDRO ROSILES SOTO</li>
<li>EDUWIGIS BUSTOS</li>
<li>LETICIA GONZALEZ</li>
<li>ANGEL PEREZ</li>
<li>EVARISTO FLORES</li>
<li>BLANCA OSUNA</li>
<li>RAUL UGALDE ROJAS</li>
<li>MIREYDI LUGO RESENDIZ</li>
<li>JOSE IGNACIO DIAZ</li>
<li>MARIA GUADALUPE FLORES GASCA</li>
<li>SALVADOR MARTINEZ</li>
<li>JUANVICTOR SANTA MARIA FAVELA</li>
<li>GEORGINA MEJORADA MARTINEZ</li>
<li>JAVIER VELÁZQUEZ</li>
<li>ROBERTO NAVA</li>
<li>ELIAS MENDOZA</li>
<li>CATALINA DELGADO</li>
<li>AIDE GARCÍA</li>
<li>SILVIA BEATRIZ CHIAPPINI CECIAS</li>
<li>CATALINA AGUILAR</li>
<li>RAMSES SALAZAR</li>
<li>ANGEL SOBERANIS</li>
<li>LUIS SALGADO</li>
<li>JOSEANTONIO SILVATAPIA</li>
<li>MARIAESTHER ANAYAGARCIA</li>
<li>IVONNE VAZQUEZ</li>
<li>FRANCISCO ALVAREZ</li>
<li>LILIA VELAZQUEZ MENDOZA</li>
<li>SOFÍA HERÁNDEZ ALAMILLA</li>
<li>CLAUDIA RAMOS FLORES</li>
<li>LETICIA GARCIA LICEA</li>
<li>PAOLA NAVA</li>
<li>RAUL OLIMPO AVILA GOMEZ</li>
<li>MARIANA ESPINOZA</li>
<li>GONZALO IBARRA</li>
<li>VICTOR ADRIÁN VELÁZQUEZ PÉREZ</li>
<li>GUILLERMO IVAN TREJO RIVERO</li>
<li>JOSELUIS SANDOVAL GONZALEZ</li>
<li>RAUL LOPEZ</li>
<li>MARÍA JESUS JUAREZ MUÑOZ</li>
<li>ROBERTO ALEMAN SAM</li>
<li>RICARDO SÁNCHEZ ARCOS</li>
<li>RAFAEL RAMOS ALEJANDRE</li>
<li>PATRICIA ORTEGA</li>
</ul>
			


		</div>
	</div>

	<div class="row">
		<div class="col-md-4" style="background: rgba(0,173,239,.05)">
			<div class="titulo">Jalisco</div>

<ul class="lista">
<li>LUIS IGNACIO ESCOBAR BELTRÁN</li>
<li>ERNESTO SEGURA</li>
<li>JUANCARLOS SUAREZ</li>
<li>DULCE MONTERO</li>
<li>MAYRA LÓPEZ</li>
<li>VICTOR TORRES</li>
<li>FABIÁN VALENZUELA</li>
<li>JUAN PALACIOS</li>
<li>MARTHA OSEGUERA GUTIERREZ</li>
<li>MONTSERRAT OLEA HERNANDEZ</li>
<li>GABRIEL AGUILAR</li>
<li>JORGE ORTIZ GARCIA</li>
<li>SAUL ALFARO</li>
<li>STEPHANY MADRIGAL</li>
<li>LUIS OCTAVIO HERNANDEZ GUEVARA</li>
<li>FIORELLA GARCÍA</li>
<li>RIGOBERTO GUTIERREZ</li>
<li>ENRIQUE AVALOS</li>
<li>TERESA DIAZ</li>
<li>ISRAEL AMADOR</li>
<li>EDSON GRAJEDA</li>
<li>DARIO HUMBERTO GONZALEZ GARCIA</li>
<li>SALVADOR RODRIGUEZ</li>
<li>JOANA MACIEL OCHOA</li>
<li>ALEXANDRO MONTIEL MEDINA</li>
<li>JOAQUIN VERA OCHOA</li>
<li>MARIA DEL REFUGIO ALVAREZ DELGADO</li>
<li>ERNESTO CARBAJAL CUEVAS</li>
<li>ROSA MARTHA GONZALEZ FERNANDEZ</li>
<li>ROQUE SANDOVAL</li>
<li>JESUS GUZMAN</li>
<li>CLEMENTE MEDINA PEREZ</li>
<li>MARCO ANTONIO IÑIGUEZ HERNANDEZ</li>
<li>MARCO ANTONIO RODARTE MENDEZ</li>
<li>SANDRA HERNANDEZ</li>
<li>JOSÉ RICARDO MACÍAS CÁRDENAS</li>
<li>CLAUDIA RUIZ</li>
<li>ANTONIO ALVARADO</li>
<li>HUGO HIGUERA</li>
<li>GILBERTO TABLON</li>
<li>HECTOR ALFONSO COVARRUBIAS</li>
<li>ELPIDIO PEREZ</li>
<li>IRMAYOLANDA MERAANGUIANO</li>
<li>EMILIA RUIZ MEZA</li>
<li>MARISELA PECERO</li>
<li>ANGELINA RAMIREZ</li>
<li>GUILLERMO MORELOS</li>
<li>JOSE FREGOSO</li>
<li>NIR FRUMER</li>
<li>IRMA LUZ MARIA MORIN SUAREZ</li>
<li>BELEN GUADALUPE FLORES BENAVIDES</li>
<li>OSCAR GUSTAVO SILVA PINTO</li>
<li>MARCELA AREVALO</li>
<li>JOSÉ ÁNGEL ACEVES</li>
<li>JOSEFINA ROCHA</li>
<li>SANDRA AGUIRRE</li>
<li>ILEANA OSORNO</li>
<li>RAUL VELAZQUEZ</li>
<li>ADRIAN ZAVALA</li>
<li>JOSÉ LUIS LOPEZ ROMO</li>
<li>SANDRA MORA</li>
<li>ANA CRISTINA MIRAMONTES MARTINEZ</li>
<li>CARLOS JESUS PRADO GARCIDUEÑAS</li>
<li>RITA MARTÍNEZ</li>
<li>KARINA MARTINEZ</li>
<li>JUANA ÁLVAREZ</li>
<li>CECILIA SANTAMARIA</li>
<li>RODRIGO MORA</li>
<li>ISRAEL REQUENES</li>
<li>ROCIOEDITH LOPEZ PLASCENCIA</li>
<li>JUAN ALVAREZ</li>
<li>ARTURO MARTINEZ</li>
<li>ANGEL ROJO VIZCARRA</li>
<li>ABIMELEC MORALES</li>
<li>JUAN VERA</li>
<li>BERNARDO JIMENEZ SANTANA</li>
</ul>
		</div>
		<div class="col-md-4">
			<div class="titulo">Tampico</div>
<ul class="lista">
<li>BLANCA DEL ANGEL DE LEY</li>
<li>ALFREDO DIAZ</li>
<li>BLANCA PARRA</li>
<li>JAIME CELIS</li>
<li>DAVID ALEJANDRO GALINDO AGUILAR</li>
<li>GONZALO ANTONIO FERNANDEZ DE LARA</li>
<li>LUCIA LETICIA RIVERA</li>
<li>MARTHA SALAZAR</li>
<li>ESTUARDO CIRO DEL ANGEL</li>
<li>JOSÉ EDINSO MORÁN CERÓN</li>
<li>LUIS JOVANY SEGURA CÓRDOVA</li>
<li>LIDIA JUANA GONZÁLEZ LÓPEZ</li>
<li>VICTOR HUGO LLOVERA RAMÍREZ</li>
<li>MARIA MAGDALENA BRICENO VAZQUEZ</li>
<li>JORGE ALBERTO PÉREZ PONCE</li>
<li>MARIA PEREZ</li>
<li>CARLOS MAYA</li>
<li>MARIA DEL ROSARIO PÉREZ LÓPEZ</li>
<li>SOCORRO PULIDO DOMINGUEZ</li>
<li>YOLANDA BAUTISTA</li>
<li>CARLOS AMADOR</li>
<li>MAYRA PATRICIA HINOJOSA MENDOZA</li>
<li>SANDRA PATRICIA RODRIGUEZ CONTRERAS</li>
<li>CLAUDIA VAZQUEZ</li>
<li>JUANJOSE MELLADO</li>
<li>LUIS CHAVEZ</li>
<li>MARCO ANONIO VIZCARRA ROMERO</li>
<li>FERNANDO MENDO</li>
<li>MA CONCEPCION GRANADOS HERNANDEZ</li>
<li>ALEJANDRA GONZALEZ</li>
<li>VICTOR BARRIOS</li>
<li>AURORA VALDOVINOS</li>
<li>MA GUADALUPE URIZA CASTELAN</li>
</ul>

		</div>
		<div class="col-md-4" style="background: rgba(0,173,239,.05)">
			<div class="titulo">Matamoros</div>

<ul class="lista">
<li>ÓSCAR EDUARDO MACHUCA GALLEGOS</li>
<li>HORTENCIA PERALES</li>
<li>JOSE FLORES</li>
<li>ALEJANDRO ROMERO</li>
<li>LUIS DELBOSQUE</li>
<li>HECTOR CESAR GUTIERREZ SANCHEZ</li>
<li>JULIETA VELA</li>
<li>FERNANDO DIAZ PEREZ</li>
<li>EFRAIN PELAYO VELASCO</li>
<li>RODOLFO FRAUSTO</li>
<li>JOSE SERGIO CORDOVA</li>
<li>JUAN GABRIEL MONITA CARREÑO</li>
<li>BLANCA SALINAS</li>
<li>MARISA DE JESUS BENAVIDES GONZALEZ</li>
<li>ENEDELIA NORATO</li>
<li>RICARDO ALVARADO</li>
<li>RAUL RODRIGUEZ</li>
<li>ELOISA MENDOZA</li>
<li>JUAN GARCIA</li>
<li>MARIA ENCARNACION AGUILAR</li>
<li>SELENE VELAZQUEZ</li>
<li>MAGDALENA SIERRA</li>
<li>ANGEL ANTONIO CARRANCO GONZÁLEZ</li>
<li>LUZ LOPEZ</li>
<li>JOSE BRAÑA</li>
<li>ELIUD ALONSO</li>
<li>LAURA TERESA RODRIGUEZ CISNEROS</li>
<li>JOSE RODRIGUEZ</li>
<li>JAVIER SOLIS CORDOVA</li>
<li>JORGE DUARTE</li>
<li>RENE COMPEAN</li>
<li>ALMA ALMAGUER</li>
<li>GABRIEL HERRERA</li>
</ul>


		</div>
	</div>

	<div class="row">
		<div class="col-md-4">
			<div class="titulo">Reynosa</div>

<ul class="lista">
<li>LUIS SOSA</li>
<li>CARLOS VAZQUEZ</li>
<li>GUILLERMO CABALLERO</li>
<li>KARINA CASTILLO</li>
<li>MARCO AURELIO RUVALCABA</li>
<li>REYNA CASTILLO</li>
<li>CARLOS YEPEZ</li>
<li>MIGUEL SEGURA</li>
<li>VICTOR VILLALON</li>
<li>HUMBERTO RAMIREZ</li>
<li>EDGARARNALDO CEPEDATORRES</li>
<li>ADA ILEANA MENCHACA BARRUETA</li>
<li>RENE BELTRAN</li>
<li>ROLANDO GARCIA ENRIQUEZ</li>
<li>TIRSO LOPEZ</li>
<li>MYRIAM MALDONADO</li>
<li>IVAN RIVERA</li>
<li>ABEL DE LA CRUZ SANTIAGO</li>
<li>BENITO HERNÁNDEZ</li>
<li>RICARDO JAIME MONTESINOS MENDOZA</li>
<li>VICTOR GONZALEZ</li>
<li>LUIS ERIK GUTIERREZ</li>
<li>RICARDO ZUÑIGA</li>
<li>JOSE ORTIZ</li>
<li>LUIS ALBERTO ORTIZ DEL TORO</li>
<li>ELIZABETH VAZQUEZ GONZALEZ</li>
<li>FERNANDO TRONCOSO</li>
<li>FERMIN ORTEGA</li>
<li>RENE CIPRIANO GUTIERREZ</li>
<li>KARLA ANAHY RODRIGUEZ MOLINA</li>
<li>NORMA GARCIA</li>
<li>KARLA ALANIS</li>
<li>RAUL NORBERTO SANDOVAL VANOYE</li>
</ul>


		</div>
		<div class="col-md-4"></div>
		<div class="col-md-4"></div>
	</div>



</div>